# Generated by Django 5.2.17 on 2026-08-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('BASE', 'BASE'), ('MILK', 'MILK'), ('SWEETENER', 'SWEETENER'), ('ADDON', 'ADDON')], max_length=20)),
                ('stock_quantity', models.FloatField(default=1000)),
                ('unit', models.CharField(default='g', max_length=10)),
                ('low_threshold', models.FloatField(default=50)),
            ],
        ),
    ]
