# Generated by Django 5.2.17 on 2026-08-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Walk-in', max_length=100)),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('VALIDATING', 'VALIDATING'), ('CONFIRMED', 'CONFIRMED'), ('PREPARING', 'PREPARING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
